name: Update requirements
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
           pip install pipreqs
           pipreqs --force --mode gt

      - name: Commit and push changes
        run: |
           git config --global user.name "${GITHUB_ACTOR}"
           git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
           git add requirements.txt && \
              git commit -m "Updated $INPUT_PROJECT_NAME requirements file" && \
              git push -u origin HEAD
