name: Check licenses

on:
  push:
    branches:
      - master

env:
  DEP_PATH: requirements.txt

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install
        run: |
           pip install pipreqs
           pipreqs --force --mode gt

      - name: Commit and push changes
        run: |
           git config --global user.name "${GITHUB_ACTOR}"
           git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
           git add requirements.txt
           git commit -m "Updated $INPUT_PROJECT_NAME requirements file" || exit 0
           git push -u origin HEAD

  check:
    needs: update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Python License Check
        uses: aufdenpunkt/python-license-check-action@main
