name: Check licenses

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install
        run: |
           pip install pipreqs
           pipreqs --force --mode gt

      - name: Commit and push changes
        run: |
           git config --global user.name "${GITHUB_ACTOR}"
           git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
           git add requirements.txt
           git commit -m "Updated ${INPUT_PROJECT_NAME} requirements file" && \
             echo "CHECK=true" >> "${GITHUB_ENV}" || \
             echo "CHECK=false" >> "${GITHUB_ENV}"
           git push -u origin HEAD

  check:
    if: ${{ env.CHECK == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Python License Check
        run: |
           pip install liccheck
           pip install -r requirements.txt
           liccheck -s .strategy -r requirements.txt --no-deps
