name: Update requirements
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
           pip install pipreqs
           pipreqs --force --mode gt
